dj_brain_system/api/v1/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import SimpleRouter

from api.v1.views import QuestionViewSet

app_name = 'api'

router_questions = SimpleRouter()
router_questions.register(
    r'questions',
    QuestionViewSet,
    basename='questions'
)

urlpatterns = [
    path(
        'info/',
        TemplateView.as_view(template_name='api/api_info.html'),
        name='info'
    ),
    path('', include(router_questions.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

dj_brain_system/common_pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'common_pages'

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='common_pages/main.html'),
        name='main'
    ),
    path(
        'legal/',
        TemplateView.as_view(template_name='common_pages/legal.html'),
        name='legal'
    ),
    path(
        'feedback/',
        views.feedback,
        name='feedback'
    ),
]

dj_brain_system/dj_brain_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('common_pages.urls')),
    path('brain_system/', include('brain_system.urls')),
    path('questions/', include('questions.urls')),
    path('admin-site/', admin.site.urls),
    path('api/v1/', include('api.v1.urls')),
    path('auth/', include('users.urls'))
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'common_pages.views.page_not_found'
handler403 = 'common_pages.views.forbidden'
handler400 = 'common_pages.views.bad_request'
handler500 = 'common_pages.views.internal_server_error'

schema_view = get_schema_view(
    openapi.Info(
        title="Brain API",
        default_version='v1',
        description="Brain API description",
        terms_of_service="https://db.chgk.info/copyright",
        license=openapi.License(name="CC BY-SA 4.0 Deed"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    path(
        'api/v1/redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]

dj_brain_system/questions/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.questions, name='questions'),
    path(
        'telegram-bot/',
        TemplateView.as_view(template_name='questions/tg_bot.html'),
        name='tg-bot'
    ),
    path(
        'add/',
        views.add_question,
        name='add'
    ),
]

dj_brain_system/users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm
from .views import UserDeleteView, UserUpdateView

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('profile/<username>/', UserUpdateView.as_view(), name='profile'),
    path('delete/<username>', UserDeleteView.as_view(), name='delete'),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name="password_change_done",
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    path(
        'registration/',
        CreateView.as_view(
            template_name='users/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
]

dj_brain_system/templates/includes/footer.html
{% load static %}


<div class="container border-top">

  <div class="row align-items-center pt-2 pb-2">
    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 col-xxl-4 pb-2 order-xs-3 order-sm-3 order-md-3 order-lg-3 order-xl-1 order-xxl-1">
      <div class="text-center text-body-secondary adaptive-fs">
        © 2024 brainsystem.sytes.net
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 col-xxl-4 pb-2 order-xs-1 order-sm-1 order-md-1 order-lg-1 order-xl-2 order-xxl-2">
      <div class="justify-content-center adaptive-fs">
        <a href="#top" class="d-flex align-items-center justify-content-center link-body-emphasis text-decoration-none">
          <img class="bi me-2" width="40" height="40" src="{% static 'img/up_arrow.png' %}"></img>
        </a>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 col-xxl-4 pb-2 order-xs-2 order-sm-2 order-md-2 order-lg-2 order-xl-3 order-xxl-3">
      <div class="justify-content-center adaptive-fs">
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav justify-content-center">
          <li class="nav-item"><a href="{% url 'common_pages:legal' %}" class="{% if view_name == 'common_pages:legal' %} disabled {% endif %} nav-link link-dark">Условия использования</a></li>
          <li class="nav-item"><a href="{% url 'common_pages:feedback' %}" class="{% if view_name == 'common_pages:feedback' %} disabled {% endif %} nav-link link-dark">Обратная связь</a></li>
        </ul>
        {% endwith %}
      </div>
    </div>
  
  </div>
</div>

dj_brain_system/templates/includes/header.html
{% load static %}


<div class="container border-bottom">

  <div class="row align-items-center">
    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 col-xxl-6 pb-2 pt-3">
        <a href="{% url 'common_pages:main' %}" class="d-flex align-items-center justify-content-center text-dark text-decoration-none">
          <img class="bi me-2" width="40" height="40" role="img" src="{% static 'img/logo.png' %}"></img>
          <span class="adaptive-fs-big">Brain System</span>
          </a>
    </div>



    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 col-xxl-6 pb-2 pt-3">
      <div class="justify-content-center">
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav justify-content-center text-center adaptive-fs">

          {% comment %} <li><a href="{% url 'questions:questions' %}" class="{% if view_name == 'questions:questions' %} disabled {% endif %} nav-link px-2 link-dark">База вопросов</a></li>
          <li><a href="{% url 'questions:tg-bot' %}" class="{% if view_name == 'questions:tg-bot' %} disabled {% endif %} nav-link px-2 link-dark">Telegram-бот</a></li>
          <li><a href="{% url 'api:info' %}" class="{% if view_name == 'api:info' %} disabled {% endif %} nav-link px-2 link-dark">BrainAPI</a></li> {% endcomment %}
          
          <div class="dropdown adaptive-fs px-1">
            <button class="btn btn-outline-secondary dropdown-toggle adaptive-fs" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Документация
            </button>
            <ul class="dropdown-menu adaptive-fs-small">
              <li><a class="dropdown-item {% if view_name == 'brain_system:operating' %} disabled {% endif %}" href="{% url 'brain_system:operating' %}">Описание работы</a></li>
              <li><a class="dropdown-item {% if view_name == 'brain_system:circuit' %} disabled {% endif %}" href="{% url 'brain_system:circuit' %}" href="#">Электрическая схема</a></li>
              <li><a class="dropdown-item {% if view_name == 'brain_system:pcb' %} disabled {% endif %}" href="{% url 'brain_system:pcb' %}">Печатная плата</a></li>
              <li><a class="dropdown-item {% if view_name == 'brain_system:printed' %} disabled {% endif %}" href="{% url 'brain_system:printed' %}">Печатные детали</a></li>
              <li><a class="dropdown-item {% if view_name == 'brain_system:bought' %} disabled {% endif %}" href="{% url 'brain_system:bought' %}">Покупные изделия</a></li>
              <li><a class="dropdown-item {% if view_name == 'brain_system:firmware' %} disabled {% endif %}" href="{% url 'brain_system:firmware' %}">Программное обеспечение</a></li>
            </ul>
          </div>


          <div class="dropdown adaptive-fs px-1">
            <button class="btn btn-outline-secondary dropdown-toggle adaptive-fs" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              База вопросов
            </button>
            <ul class="dropdown-menu adaptive-fs-small">
              <li><a class="dropdown-item {% if view_name == 'questions:questions' %} disabled {% endif %}" href="{% url 'questions:questions' %}">Случайные вопросы из Базы</a></li>
              <li><a class="dropdown-item {% if view_name == 'questions:add' %} disabled {% endif %}" href="{% url 'questions:add' %}" href="#">Добавить вопрос в Базу</a></li>
              <li><a class="dropdown-item {% if view_name == 'api:info' %} disabled {% endif %}" href="{% url 'api:info' %}">BrainAPI</a></li>
              <li><a class="dropdown-item {% if view_name == 'questions:tg-bot' %} disabled {% endif %}" href="{% url 'questions:tg-bot' %}">Telegram-бот</a></li>
            </ul>
          </div>

          {% if user.is_authenticated %}
            <a class="nav-link text-secondary" href="{% url 'profile' user.username %}">{{ user.username }}</a>
            {% comment %} <span class="navbar-text text-secondary fw-bold ms-2">{{ user.username }}</span> {% endcomment %}
            <li class="nav-item">
              <a class="nav-link text-secondary" href="{% url 'logout' %}">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="text-secondary nav-link fw-bolder {% if view_name == 'login' %} active {% endif %}" href="{% url 'login' %}">Войти</a>
            </li>

          {% endif %}






        </ul>
        {% endwith %}
      </div>
    </div>
  
  </div>
</div>

dj_brain_system/templates/includes/questions_paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.number != 1 %}
    <li class="page-item">
      <a class="page-link" href="?page=1">
        Первая
      </a>
    </li>
    {% endif %}
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
        {{ page_obj.previous_page_number }}
      </a>
    </li>
    {% endif %}
    <li class="page-item disabled"><a class="page-link" href="">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        {{ page_obj.next_page_number }}
      </a>
    </li>
    {% endif %}
    {% if page_obj.number != page_obj.paginator.num_pages %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
        Последняя
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}