dj_brain_system/brain_system/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views

app_name = 'brain_system'

urlpatterns = [
    path(
        'operating-principle/',
        TemplateView.as_view(
            template_name='brain_system/operating_principle.html'
        ),
        name='operating'
    ),
    path(
        'electric-schematics/',
        TemplateView.as_view(template_name='brain_system/circuit.html'),
        name='circuit'
    ),
    path(
        'pcb/',
        TemplateView.as_view(template_name='brain_system/pcb.html'),
        name='pcb'
    ),
    path(
        'printed-parts/',
        TemplateView.as_view(template_name='brain_system/printed_parts.html'),
        name='printed'
    ),
    path(
        'bought-in-products/',
        cache_page(60 * 60)(views.ProductsListView.as_view()),
        name='bought'
    ),
    path(
        'firmware/',
        TemplateView.as_view(template_name='brain_system/firmware.html'),
        name='firmware'
    ),
    path(
        'export_model_to_ods/',
        views.export_model_to_ods,
        name='export_model_to_ods'
    ),
]

dj_brain_system/dj_brain_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('common_pages.urls')),
    path('brain_system/', include('brain_system.urls')),
    path('questions/', include('questions.urls')),
    path('admin-site/', admin.site.urls),
    path('api/v1/', include('api.v1.urls')),
    path('auth/', include('users.urls'))
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'common_pages.views.page_not_found'
handler403 = 'common_pages.views.forbidden'
handler400 = 'common_pages.views.bad_request'
handler500 = 'common_pages.views.internal_server_error'

schema_view = get_schema_view(
    openapi.Info(
        title="Brain API",
        default_version='v1',
        description="Brain API description",
        terms_of_service="https://db.chgk.info/copyright",
        license=openapi.License(name="CC BY-SA 4.0 Deed"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    path(
        'api/v1/redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]

dj_brain_system/users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm
from .views import UserDeleteView, UserUpdateView

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('profile/<username>/', UserUpdateView.as_view(), name='profile'),
    path('delete/<username>', UserDeleteView.as_view(), name='delete'),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name="password_change_done",
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    path(
        'registration/',
        CreateView.as_view(
            template_name='users/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
]

dj_brain_system/brain_system/models.py
from django.db import models


class Unit(models.Model):
    """Таблица узлов, в которые входят покупные детали."""
    name = models.CharField(
        max_length=64,
        verbose_name='Название',
        help_text='Деталь входит в состав:'
    )

    class Meta:
        verbose_name = 'Покупная деталь в составе'
        verbose_name_plural = 'Покупные детали в составе'

    def __str__(self):
        return self.name


class BoughtInProduct(models.Model):
    """Основная таблица покупных деталей."""
    name = models.CharField(
        max_length=64,
        verbose_name='Название',
        help_text='Название детали',
    )
    unit = models.ForeignKey(
        Unit,
        on_delete=models.SET_NULL,
        verbose_name='В составе',
        related_name='product_as_a_part_of',
        null=True,
        help_text='Деталь входит в состав:',
    )
    quantity = models.PositiveSmallIntegerField(
        verbose_name='Количество',
        help_text='Количество:',
    )
    product_type = models.CharField(
        max_length=128,
        verbose_name='Тип',
        blank=True,
        help_text='Тип',
    )
    comment = models.CharField(
        max_length=512,
        verbose_name='Комментарий',
        blank=True,
        help_text='Комментрий',
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Покупная деталь'
        verbose_name_plural = 'Покупные детали'

    def __str__(self):
        return self.name


class BoughtInProductLink(models.Model):
    """Таблица ссылок на покупные детали в интернет-магазинах."""
    product = models.ForeignKey(
        BoughtInProduct,
        on_delete=models.CASCADE,
        verbose_name='Объект ссылки',
        related_name='link_for_product',
        blank=True,
        null=True
    )
    link = models.URLField(
        max_length=300,
        verbose_name='URL-адрес',
        blank=True,
        null=True,
        help_text='Ссылка на деталь',
    )
    link_short_name = models.CharField(
        max_length=128,
        verbose_name='Короткое название ссылки',
        blank=True,
        null=True,
        help_text='Короткое название ссылки для таблицы на сайте',
    )

    class Meta:
        verbose_name = 'Ссылка на покупную деталь'
        verbose_name_plural = 'Ссылки на покупные детали'

    def __str__(self):
        return self.link_short_name

dj_brain_system/brain_system/views.py
import pandas as pd
from django.http import FileResponse
from django.views.generic import ListView

from .models import BoughtInProduct
from .services import get_base_queryset, unite_rows_with_multiple_links


class ProductsListView(ListView):
    """Class for page with bought-in products table generation."""
    model = BoughtInProduct
    queryset = get_base_queryset()
    template_name = 'brain_system/bought_in_products.html'


def export_model_to_ods(request):
    product_list = list(
        get_base_queryset().values(
            'name',
            'unit__name',
            'quantity',
            'product_type',
            'link_for_product__link',
            'comment'
        )
    )
    product_list = unite_rows_with_multiple_links(product_list)
    df = pd.DataFrame(product_list)
    df = df.rename(columns={
        'name': 'Название',
        'unit__name': 'Входит в состав',
        'quantity': 'Кол-во',
        'product_type': 'Тип',
        'link_for_product__link': 'Ссылки',
        'comment': 'Комментарий'
    })
    with pd.ExcelWriter('static_dev/brain_system_BOM.ods',
                        engine='odf') as doc:
        df.to_excel(doc, sheet_name='Bought-in poducts')
    return FileResponse(
        open('static_dev/brain_system_BOM.ods', 'rb'),
        as_attachment=True
    )

dj_brain_system/templates/brain_system/bought_in_products.html
{% extends "brain_system/manual.html" %}
{% load static %}
{% block manual_title %}
  Покупные изделия
{% endblock %}

{% block manual_pages %}
<div class="ms-4 adaptive-fs">
  <h2 class="ms-4 adaptive-fs-title" style="text-align: center;">Покупные изделия</h2>
  <br>
  <p>В приведенной таблице представлены покупные изделия, необходимые для сборки брейн-системы.</p>
  <p>Ссылки на детали в интернет-магазинах не являются референтными и представлены для дополнительной информации о характеристиках и внешнем виде деталей.</p>
  <p>Мелочь (метизы, электронные компоненты и т.п.) лучше брать с запасом.</p>
  <p>
    <form action="{% url 'brain_system:export_model_to_ods' %}" target="_blank">
      <button type="submit" class="btn btn-outline-secondary adaptive-fs-small">Выгрузить данные таблицы в формате ods</button>
    </form>
  </p>
  <table style="font-size: 14px;" class="table table table-bordered table-striped-columns table-hover">
    <thead class="align-middle text-center">
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Входит в состав</th>
        <th scope="col">Кол-во</th>
        <th scope="col">Тип</th>
        <th scope="col">Ссылка</th>
        <th scope="col">Комментарий</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for product in object_list %}
      <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.unit }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.product_type }}</td>
        <td>
          {% for link in product.link_for_product.all %}
            <a href="{{ link.link }}" class="link-secondary" target="_blank" download>{{ link.link_short_name }}</a><br>
          {% endfor %}
        </td>
        <td>{{ product.comment }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

dj_brain_system/templates/brain_system/circuit.html
{% extends "brain_system/manual.html" %}
{% load static %}
{% block manual_title %}
  Электрическая схема
{% endblock %}
{% block manual_pages %}

<div  class="ms-4 adaptive-fs">
  <h2 class="ms-4 adaptive-fs-title" style="text-align: center;">Электрическая схема</h2>
  <br>


  <div class="text-center">
    <img class="border-3 rounded w-75" data-bs-toggle="modal" data-bs-target="#exampleModal" src="{% static 'img/manual_circuit/bs_electrical_diagram.png' %}">
  </div>
  <br>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <img class="border-3 rounded img-fluid" src="{% static 'img/manual_circuit/bs_electrical_diagram.png' %}">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>
  <p>
    Плата имеет два ввода питания: DC 12V (питание платы Arduino и светодиодов на главном блоке) и DC 24V (питание блока светодиодов). Сетевое напряжение преобразуется в AC-DC-блоке питания, затем напряжение 24V снижется до 12V на DC-DC-преобразователе.
  </p>
  <p>
    Для подачи напряжения на блок светодиодов используются реле на основе MOSFET-транзисторов.
  </p>
  <div class="accordion" id="ImgAccordion">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#MOSFET-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
          Схема подключения нагрузки через MOSFET
        </button>
      </h2>
      <div id="MOSFET-collapseOne" class="accordion-collapse collapse">
        <div class="accordion-body">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{% static 'img/manual_circuit/load_connection_via_MOSFET.png' %}">
        </div>
      </div>
    </div>
  </div>
  <br>
  <p>
    Для устранения «дребезга» контактов применена схема на основе шестиканального <a href="https://vpayaem.ru/inf_drebezg.html" class="link-secondary" target="_blank">триггера Шмитта</a>.
  </p>
  <p>
    Электрическая схема брейн-системы:<br>
    <a href="{% static 'files/manual_circuit/bs_electrical_diagram.pdf' %}" class="link-secondary" download>скачать в формате pdf</a><br>
    <a href="{% static 'files/manual_circuit/bs_electrical_diagram.vsd' %}" class="link-secondary" download>скачать в формате vsd</a><br>
  </p>
</div>
</div>
{% endblock %}

dj_brain_system/templates/brain_system/firmware.html
{% extends "brain_system/manual.html" %}
{% load static %}
{% block manual_title %}
  Программное обеспечение
{% endblock %}
{% block manual_pages %}
<div class="ms-4 adaptive-fs">
  <h2 class="ms-4 adaptive-fs-title" style="text-align: center;">Программное обеспечение</h2>
  <p>
    <br>
    Скачать скетч:<br>
    <li><a href="{% static 'files/manual_firmware/BrainSystem.zip' %}" class="link-secondary adaptive-fs-small" download>zip-архив</a></li>
    <li><a href="https://github.com/wake-lift/brain_system" class="link-secondary adaptive-fs-small" target="_blank">GitHub</a></li>
    <br>
  </p>
  <p>
    Для обработки кнопок ведущего и игроков используются <a href="https://deepbluembedded.com/arduino-pcint-pin-change-interrupts/" class="link-secondary" target="_blank">Pin Change Interrupts</a>.<br>
    С этим связан выбор пинов на плате Arduino и соответствующая разводка дорожек на печатной плате.
  </p>
  <p>
    Инструкцию по заливке скетча в Arduino 
    <a href="https://support.arduino.cc/hc/en-us/articles/4733418441116-Upload-a-sketch-in-Arduino-IDE" class="link-secondary" target="_blank">несложно</a> 
    <a href="https://www.electronicsforu.com/technology-trends/learn-electronics/how-to-upload-source-code-on-arduino-board" class="link-secondary" target="_blank">найти</a> 
    <a href="https://wiki.iarduino.ru/page/ustanovka-nastroyka-programmnoy-obolochki-arduino-ide-dlya-windows/" class="link-secondary" target="_blank">в сети</a>.
    <br><br>
    Код скетча подробно прокомментирован. Можно изменить многие параметры, например:
    <ul>
      <li>
        Время, отведенное командам на ответ
      </li>
      <li>
        Частоту мерцания светодиодов
      </li>
      <li>
        Длительность и тональность звуковых сигналов
      </li>
    </ul>
  </p>
</div>
{% endblock %}

dj_brain_system/templates/brain_system/manual.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% block manual_title %}{% endblock %}
{% endblock %}

{% block content %}
<div class="container-fluid">
<div class="row justify-content-center">
  <div class="col-xxl-3 border-end border-3 d-none d-xxl-block">
    <div class="container sticky-top">
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link link-dark {% if view_name == 'brain_system:operating' %} disabled {% endif %}" href="{% url 'brain_system:operating' %}">Описание работы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark {% if view_name == 'brain_system:circuit' %} disabled {% endif %}" href="{% url 'brain_system:circuit' %}">Электрическая схема</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark {% if view_name == 'brain_system:pcb' %} disabled {% endif %}" href="{% url 'brain_system:pcb' %}">Печатная плата</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark {% if view_name == 'brain_system:printed' %} disabled {% endif %}" href="{% url 'brain_system:printed' %}">Печатные детали</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark {% if view_name == 'brain_system:bought' %} disabled {% endif %}" href="{% url 'brain_system:bought' %}">Покупные изделия</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark {% if view_name == 'brain_system:firmware' %} disabled {% endif %}" href="{% url 'brain_system:firmware' %}">Программное обеспечение</a>
        </li>
      </ul>
      {% endwith %}
    </div>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 col-xl-12 col-xxl-9">
    {% block manual_pages %}{% endblock %}
  </div>
</div>
</div>
{% endblock %}

dj_brain_system/templates/brain_system/operating_principle.html
{% extends "brain_system/manual.html" %}
{% load static %}
{% block manual_title %}
  Принцип работы
{% endblock %}
{% block manual_pages %}
<div>
  <h2 class="ms-4 adaptive-fs-title" style="text-align: center;">Работа брейн-системы</h2>
  <br>
  <div class="d-flex justify-content-center">
    <video class="w-100" controls >
      <source src="{% static 'video/bs_demo.mp4' %}" type="video/mp4" />
    </video>
  </div>
  <div class="ms-4 adaptive-fs"> 
    <br>
    <p>Брейн-система состоит из:</p>
    <ul class="ms-4 adaptive-fs-small">
      <li>базовой станции</li>
      <li>блока светодиодов</li>
      <li>4-х кнопок игроков</li>
    </ul>
    <p>На базовой станции расположены:</p>
    <ul class="ms-4 adaptive-fs-small">
      <li>выключатель питания 220В</li>
      <li>тумблер выбора режима игры (брейн-ринг — ЧГК — эрудит-квартет)</li>
      <li>кнопка подтверждения выбора режима игры</li>
      <li>две кнопки ведущего («SET» и «RESET»)</li>
      <li>зуммер для подачи звуковых сигналов</li>
    </ul>
    <div class="accordion text-center" id="ImgAccordion">
      <div class="accordion-item w-100">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
            Базовая станция - вид спереди
          </button>
        </h2>
        <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse">
          <div class="accordion-body">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{% static 'img/manual_operation_principle/base_station_front.jpg' %}">
          </div>
        </div>
      </div>
      <div class="accordion-item w-100">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
            Базовая станция - вид сзади
          </button>
        </h2>
        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
          <div class="accordion-body">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{% static 'img/manual_operation_principle/base_station_back.jpg' %}">
          </div>
        </div>
      </div>
      <div class="accordion-item w-100">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
            Базовая станция - вид сбоку
          </button>
        </h2>
        <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
          <div class="accordion-body">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{% static 'img/manual_operation_principle/base_station_side.jpg' %}">
          </div>
        </div>
      </div>
    </div>
    <p>
      <br>
      К базовой станции подключаются:
      <ul class="ms-4 adaptive-fs-small">
        <li>Кнопки игроков с кнопками. Максимальное количество команд — 4 (красные, синие, зеленые, жёлтые)</li>
        <li>Блок светодиодов. На блоке в зависимости от действий ведущего и команд загораются светодиоды 5-ти цветов (белый, красный, синий, зелёный, жёлтый). Для удобства ведущего (блок светодиодов обычно повернут к игрокам, и ведущий не видит его светодиоды) светодиоды продублированы на базовой станции.</li>
      </ul>
    </p>
    <p>
      Чтобы выбрать один из трёх режимов игры, ведущий переводит тумблер в нужное положение и подтверждает выбор нажатием кнопки «SET MODE»
    </p>
    <div class="accordion" id="ModesAccordion">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#ModesAccordion-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
            Режим игры «Брейн-ринг»
          </button>
        </h2>
        <div id="ModesAccordion-collapseOne" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
          <div class="accordion-body">
            <p>
              Для игры в «брейн-ринг» необходим ведущий и от 2-х до 4-х команд.
            </p>
            <p>
              Ведущий зачитывает вопрос и кнопкой «SET» запускает таймер. Выдаётся звуковой сигнал и зажигается белый светодиод.
            </p>
            <p>
              Если команда хочет дать ответ, она нажимает на свою кнопку.
              При этом белый светодиод гаснет, загорается светодиод цвета команды, выдаётся звуковой сигнал. Кнопки других команд блокируются.
            </p>
            <p>
              Если команда дала правильный ответ, ведущий сбрасывает раунд двумя нажатиями кнопки «RESET» и переходит к следующему вопросу.
            </p>
            <p>Если команда дала неправильный ответ, ведущий гасит светодиоды нажатием кнопки «RESET», после чего возобновляет отсчёт времени кнопкой «SET».
              При этом кнопка команды, давшей неправильный ответ, блокируется до конца раунда. Таймер настроен на 20 секунд.
              За 5 секунд до конца времени выдаются короткие ежесекундные сигналы.
            </p>
            <p>
              После того, как время вышло, звучит звуковой сигнал и кнопки всех команд блокируются. Ведущий сбрасывает раунд кнопкой «RESET» и переходит к следующему вопросу.
            </p>
            <p>Если команда нажала кнопку до старта таймера, активируется фальстарт. 
              Звучит длинный звуковой сигнал, светодиод цвета команды, допустившей фальстарт, начинает мигать. 
              Кнопки других игроков блокируются (чтобы не могло быть нескольких фальстартов одновременно). 
              Чтобы сбросить фальстарт, ведущий однократно нажимает «RESET», после чего может запустить отсчёт таймера. 
              Кнопка команды, допустившей фальстарт, блокируется до конца раунда.
            </p>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#ModesAccordion-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
            Режим игры «Что-Где-Когда»
          </button>
        </h2>
        <div id="ModesAccordion-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
          <div class="accordion-body">
            <p>
              Для проведения игр по «что-где-когда» есть более удобные средства, например сайт <a href="https://chgk-timer.ru/" class="link-secondary" target="_blank">«ЧГК-таймер»</a>. Брейн-система может оказаться полезной разве что в отсутствие интернета или компьютера. Логика игры такова:
            </p>
            <p>
              Блок светодиодов для данного режима игры не нужен. Ведущий зачитывает вопрос и запускает время (по умолчанию 1 минута) кнопкой «SET». 
              Кнопкой «RESET» можно сбросить таймер и перейти в исходное состояние.
            </p>
            <p>
              За 10 секунд до конца времени звучит короткий звуковой сигнал. 
              По истечении одной минуты звучит длинный звуковой сигнал.
            </p>
            <p>
              Дополнительно реализована логика досрочного ответа. Если команда нажмёт кнопку в течение 1-й секунды после старта таймера — прозвучит сигнал и таймер остановится.
            </p>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#ModesAccordion-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
            Режим игры «Эрудит-квартет»
          </button>
        </h2>
        <div id="ModesAccordion-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
          <div class="accordion-body">
            <p>
              Данный режим похож на режим «брейн-ринг», но в нем ведущий не запускает таймер.
            </p>
            <p>
              Игроки могут нажать кнопку в любое время, даже не дождавшись окончания вопроса. При этом кнопки соперников блокируются.
            </p>
            <p>
              Если был дан правильный ответ — ведущий кнопкой «RESET» сбрасывает раунд.<br>
              Если был дан неправильный ответ — кнопка игрока, давшего неверный ответ, блокируется.<br>
              После нажатия ведущим кнопки «RESET» остальные игроки могут продолжить игру.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}