dj_brain_system/common_pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'common_pages'

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='common_pages/main.html'),
        name='main'
    ),
    path(
        'legal/',
        TemplateView.as_view(template_name='common_pages/legal.html'),
        name='legal'
    ),
    path(
        'feedback/',
        views.feedback,
        name='feedback'
    ),
]

dj_brain_system/dj_brain_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('', include('common_pages.urls')),
    path('brain_system/', include('brain_system.urls')),
    path('questions/', include('questions.urls')),
    path('admin-site/', admin.site.urls),
    path('api/v1/', include('api.v1.urls')),
    path('auth/', include('users.urls'))
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = 'common_pages.views.page_not_found'
handler403 = 'common_pages.views.forbidden'
handler400 = 'common_pages.views.bad_request'
handler500 = 'common_pages.views.internal_server_error'

schema_view = get_schema_view(
    openapi.Info(
        title="Brain API",
        default_version='v1',
        description="Brain API description",
        terms_of_service="https://db.chgk.info/copyright",
        license=openapi.License(name="CC BY-SA 4.0 Deed"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    path(
        'api/v1/redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]

dj_brain_system/questions/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.questions, name='questions'),
    path(
        'telegram-bot/',
        TemplateView.as_view(template_name='questions/tg_bot.html'),
        name='tg-bot'
    ),
    path(
        'add/',
        views.add_question,
        name='add'
    ),
]

dj_brain_system/users/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm
from .views import UserDeleteView, UserUpdateView

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('profile/<username>/', UserUpdateView.as_view(), name='profile'),
    path('delete/<username>', UserDeleteView.as_view(), name='delete'),
    path(
        'password_change/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name="password_change_done",
    ),
    path(
        'password_reset/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    path(
        'registration/',
        CreateView.as_view(
            template_name='users/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
]

dj_brain_system/questions/models.py
from django.db import models


class Question(models.Model):
    QUESTION_TYPE_CHOICES = [
        ('Б', 'Брейн-ринг'),
        ('ДБ', 'Брейн-ринг (детский)'),
        ('И', 'Вопросы из интернета'),
        ('Л', 'Бескрылка'),
        ('Ч', 'Что-где-когда'),
        ('ЧБ', 'Что-где-когда (тренировки)'),
        ('ЧД', 'Что-где-когда (детский)'),
        ('Э', 'Эрудитка'),
        ('Я', 'Своя игра'),
    ]
    package = models.CharField(
        max_length=256,
        verbose_name='Пакет',
        blank=True,
        null=True
    )
    tour = models.CharField(
        max_length=256,
        verbose_name='Тур',
        blank=True,
        null=True
    )
    number = models.IntegerField(
        verbose_name='Номер вопроса в пакете',
        blank=True,
        null=True
    )
    question_type = models.CharField(
        choices=QUESTION_TYPE_CHOICES,
        max_length=2,
        verbose_name='Тип вопроса',
        default=QUESTION_TYPE_CHOICES[4]
    )
    question = models.TextField(
        verbose_name='Текст вопроса',
        db_index=True
    )
    answer = models.TextField(
        verbose_name='Ответ на вопрос',
    )
    pass_criteria = models.TextField(
        verbose_name='Критерий правильности ответа',
        blank=True,
        null=True
    )
    authors = models.TextField(
        verbose_name='Автор(ы) вопроса',
        blank=True,
        null=True
    )
    sources = models.TextField(
        verbose_name='Источник',
        blank=True,
        null=True
    )
    comments = models.TextField(
        verbose_name='Комментарий к ответу',
        blank=True,
        null=True
    )
    """Вопросы, которые не годятся для выдачи: содержат ссылку на изображение,
    угловые скобки, некодируемый набор символов и т.п."""
    is_condemned = models.BooleanField(
        verbose_name='Вопрос исключен из выдачи',
        default=False
    )
    is_published = models.BooleanField(
        verbose_name='Вопрос опубликован',
        default=False
    )

    class Meta:
        ordering = ('id',)
        verbose_name = 'вопросы из Базы'
        verbose_name_plural = 'Вопросы из Базы'

    def __str__(self):
        return f'{self.question[:75]} ...'

dj_brain_system/questions/forms.py
from django import forms
from django_bootstrap5.widgets import RadioSelectButtonGroup

from .models import Question


class QuestionForm(forms.Form):
    CHOICES = (
        ('Ч', 'Что-Где-Когда'),
        ('Б', 'Брейн-ринг'),
        ('Я', 'Своя игра'),
    )
    question_type = forms.ChoiceField(
        choices=CHOICES,
        initial='Ч',
        label='Выберите тип вопроса',
        help_text='',
        widget=RadioSelectButtonGroup
    )
    search_pattern = forms.CharField(
        required=False,
        min_length=3,
        label='Поиск по тексту вопроса',
        help_text='не менее трех символов',
    )
    questions_quantity = forms.IntegerField(
        required=False,
        min_value=1,
        max_value=100,
        initial=15,
        label='Количество вопросов',
        help_text='не более 100',
    )
    questions_displayed_on_page = forms.IntegerField(
        required=False,
        min_value=1,
        max_value=36,
        initial=5,
        label='Вопросов на странице',
        help_text='не более 36',
    )


class QuestionAddForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('package', 'tour', 'number', 'question_type',
                  'question', 'answer', 'pass_criteria', 'authors',
                  'sources', 'comments',)
        widgets = {
            'pass_criteria': forms.Textarea(attrs={'rows': 5, 'cols': 15}),
            'comments': forms.Textarea(attrs={'rows': 5, 'cols': 15}),
            'authors': forms.Textarea(attrs={'rows': 5, 'cols': 15}),
            'sources': forms.Textarea(attrs={'rows': 5, 'cols': 15}),
        }

dj_brain_system/questions/views.py
import random

from django.contrib.auth.decorators import login_required
from django.core.serializers import deserialize, serialize
from django.shortcuts import render

from .forms import QuestionAddForm, QuestionForm
from .models import Question
from .services import get_initial_queryset, get_pagination_obj


def questions(request):
    if request.method == 'POST':
        """Обработка запроса при отправке пользователем заполненной формы."""
        form = QuestionForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['search_pattern']:
                questions = Question.objects.filter(
                    question_type=form.cleaned_data['question_type'],
                    question__contains=form.cleaned_data['search_pattern'],
                    is_condemned=False,
                    is_published=True
                )
            else:
                questions = get_initial_queryset(
                    form.cleaned_data['question_type']
                )
            questions_quantity = min(
                form.cleaned_data['questions_quantity'],
                questions.count()
            )
            questions = random.choices(questions, k=questions_quantity)
            """Для корректной работы пагинации необходимо, чтобы
            сгенерированный случайный пакет и параметры
            запроса сохранялись в djando session."""
            serialized_data = serialize('json', questions)
            form_form = {
                'question_type': form.cleaned_data['question_type'],
                'search_pattern': form.cleaned_data['search_pattern'],
                'questions_quantity': form.cleaned_data['questions_quantity'],
                'questions_displayed_on_page': form.cleaned_data[
                    'questions_displayed_on_page'
                ],
            }
            request.session['from_form'] = form_form
            request.session['queryset'] = serialized_data
            request.session[
                'questions_displayed_on_page'
            ] = form.cleaned_data['questions_displayed_on_page']
            page_obj = get_pagination_obj(
                request,
                questions,
                form.cleaned_data['questions_displayed_on_page']
            )
            context = {'form': form,
                       'queryset': questions,
                       'page_obj': page_obj}
        else:
            context = {'form': form}
    elif request.method == 'GET' and 'page' in request.GET:
        """Обработка запроса при перемещении пользователя по страницам.
        Выборка вопросов не генерируется заново, а извлекается из
        данных django session."""
        form = QuestionForm(request.session['from_form'])
        questions = []
        for obj in deserialize('json', request.session['queryset']):
            questions.append(obj.object)
        page_obj = get_pagination_obj(
            request,
            questions,
            request.session['questions_displayed_on_page']
        )
        context = {'form': form, 'queryset': questions, 'page_obj': page_obj}
    else:
        """Обработка запроса при первоначальном заходе на страницу."""
        form = QuestionForm()
        context = {'form': form}
    return render(request, 'questions/questions.html', context)


@login_required(login_url='login')
def add_question(request):
    if request.method == 'POST':
        form = QuestionAddForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            context['form_saved'] = True
    else:
        form = QuestionAddForm()
        context = {'form': form}
        context['form_saved'] = False
    return render(request, 'questions/add_question.html', context)

dj_brain_system/templates/questions/add_question.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
Добавить вопрос в Базу
{% endblock %}

{% block content %}

{% if not form_saved %}
  <div class="col d-flex justify-content-center">
    <div class="container" style="width: 40rem;">
      <h3 class="adaptive-fs-title" style="text-align: center;">Добавить вопрос в Базу</h3><br>
      <form action="{% url 'questions:add' %}" method="post" class="form adaptive-fs">
        {% csrf_token %}
        {% bootstrap_field form.package show_label=False placeholder="Название пакета" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.tour show_label=False placeholder="Название тура" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.number show_label=False placeholder="Номер вопроса" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.question_type show_label=False placeholder="Категория вопроса *" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.question show_label=False placeholder="Текст вопроса *" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.answer show_label=False placeholder="Ответ на вопрос *" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.pass_criteria show_label=False placeholder="Критерии зачета правильного ответа" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.comments show_label=False placeholder="Комментарий к ответу на вопрос" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.authors show_label=False placeholder="Автор(ы) вопроса" field_class="adaptive-fs" %}<br>
        {% bootstrap_field form.sources show_label=False placeholder="Источники" field_class="adaptive-fs" %}<br>
        {% comment %} {% bootstrap_field form.captcha show_label=False %} {% endcomment %}
        {% bootstrap_button button_type="submit" content="Отправить" button_class="btn btn-outline-secondary adaptive-fs-big" %}
      </form>
    </div>
  </div>



  {% else %}
  <div class="col d-flex justify-content-center">
    <div class="container text-center" style="width: 40rem;">
      <p class="text-center fs-3">Спасибо! Ваш вопрос будет добавлен в Базу после модерации.</p><br>
      <form action="{% url 'questions:add' %}">
        <button type="submit" class="btn btn-outline-secondary btn-lg">Добавить следующий вопрос</button>
      </form>
      <br>
      <form action="{% url 'common_pages:main' %}">
        <button type="submit" class="btn btn-outline-secondary btn-lg">На главную</button>
      </form>
    </div>
  </div>
  {% endif %}




{% endblock %}

dj_brain_system/templates/questions/questions.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
База вопросов
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 col-xxl-3">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9">
      <h3 class="text-center adaptive-fs-title">Случайные вопросы из Базы</h3><br>
    </div>
  </div>
  <br>

  <div class="row justify-content-center adaptive-fs-small">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 col-xxl-3">
      <form action="{% url 'questions:questions' %}" method="post" class="form adaptive-fs">
        {% csrf_token %}
        {% bootstrap_field form.question_type show_label=True field_class="adaptive-fs" %}
        <br>
        {% bootstrap_field form.search_pattern show_label=False placeholder="Поиск вопросов" field_class="adaptive-fs" %}
        <br>
        {% bootstrap_field form.questions_quantity show_label=True placeholder="Количество вопросов" field_class="adaptive-fs" %}
        <br>
        {% bootstrap_field form.questions_displayed_on_page show_label=True field_class="adaptive-fs" %}
        {% bootstrap_button button_type="submit" content="Отправить" button_class="adaptive-fs-big btn btn-outline-secondary" %}
      </form>
      <br><br>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9 adaptive-fs">
      {% if form.is_valid or page_obj %}
        {% if not queryset %}
          <br>
          <h4 class="adaptive-fs-big" style="text-align: center;">По вашему запросу ничего не найдено :(</h4><br>
        {% else %}
          {% for obj in page_obj %}
            <div class="container border border-3">
              <div class="card-body">
                <p class="card-text fw-semibold">{% if obj.question_type != "Я" %} {{ obj.question }} {% else %} {{ obj.question|linebreaks }} {% endif %}</p>
              </div>
              <p class="d-inline-flex gap-1">
                <div class="text-center">
                  <button class="btn btn-outline-dark adaptive-fs-small" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ obj.id }}" aria-expanded="false" aria-controls="collapse{{ obj.id }}">
                    Показать ответ
                  </button>
                </div>
              </p>
              <div class="collapse" id="collapse{{ obj.id }}">
                <br>
                <p class="card-text fw-bold">{% if obj.question_type != "Я" %} {{ obj.answer }} {% else %} {{ obj.answer|linebreaks }} {% endif %}</p>
                <p class="card-text fst-italic">
                  {% if obj.comments != "None" %}<span class="text-decoration-underline">Комментарий:</span> {{ obj.comments }}<br>{% endif %}
                  {% if obj.pass_criteria != "None" %}<span class="text-decoration-underline">Зачёт:</span> {{ obj.pass_criteria }}<br>{% endif %}
                  {% if obj.authors != "None" %}<span class="text-decoration-underline">Автор(ы):</span> {{ obj.authors }}<br>{% endif %}
                  {% if obj.sources != "None" %}<span class="text-decoration-underline">Источник(и):</span> {{ obj.sources|urlizetrunc:40 }}<br>{% endif %}
                </p>
              </div>
            </div>
            <br>
          {% endfor %}
          <br>
        {% endif %}
      {% endif %}
      <div class="container justify-content-center">
        {% include "includes/questions_paginator.html" %}
        <br>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dj_brain_system/templates/questions/tg_bot.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Simple Brain Bot
{% endblock %}


{% block content %}
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10 col-xl-7 col-xxl-6">
      <div class="container">
        <div class="container text-center">
          <h2>
            <a href="https://t.me/SimpleBrainBot" class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover adaptive-fs-title" target="_blank">@SimpleBrainBot</a>
          </h2>
          <br>
          <br>
          <a href="https://t.me/SimpleBrainBot" target="_blank"><img class="img-fluid w-75" alt="..." src="{% static 'img/tg_bot_page/brain_bot_qr-code.png' %}"></a>
          <br>
          <br>
          <br>
        </div>
        <p class="text-center adaptive-fs">
          SimpleBrainBot - это Telegram-бот, генерирующий в ответ на запрос пользователя
          случайный вопрос из трех различных категорий:
            <div class="text-center adaptive-fs">
            <p>Что-Где-Когда<br>Брейн-ринг<br>Своя игра</p>
            </div>
        </p>
        <br><br>
      </div>
    </div>
  <div>
{% endblock %}